export const RAW_DATA = [
  {
    barcode: "IZ6A9426897731887",
    packageId: "03-218-9705",
    vendor: "Amazon",
    dataReceived: "2026-06-28 14:32",
    itemValues: "$142.50",
    weight: "2.4 kg",
    status: "In Review",
    details: {
      recipient: "J. Whitfield",
      address: "14 Cross St, London",
      items: ["USB-C Cable", "Desk Lamp", "Notebook Set"],
      carrier: "Amazon Logistics",
    },
  },
  {
    barcode: "IZ6A9423125556541887",
    packageId: "03-854-9235",
    vendor: "Amazon",
    dataReceived: "2026-06-28 17:46",
    itemValues: "$12.50",
    weight: "1.1 kg",
    status: "In Review",
    details: {
      recipient: "J. Whitfield",
      address: "14 Cross St, London",
      items: ["USB-C Cable", "Desk Lamp", "Notebook Set"],
      carrier: "Amazon Logistics",
    },
  },
  {
    barcode: "IZ6B1183420019234",
    packageId: "03-156-1255",
    vendor: "DHL",
    dataReceived: "2026-06-29 09:12",
    itemValues: "$89.00",
    weight: "1.1 kg",
    status: "Ready to Send",
    details: {
      recipient: "M. Osei",
      address: "22 Baker Rd, Manchester",
      items: ["Running Shoes"],
      carrier: "DHL Express",
    },
  },
  {
    barcode: "IZ6C7729384610552",
    packageId: "03-345-1643",
    vendor: "FedEx",
    dataReceived: "2026-06-30 18:05",
    itemValues: "$310.75",
    weight: "5.8 kg",
    status: "Action Required",
    details: {
      recipient: "R. Patel",
      address: "9 Elm Court, Bristol",
      items: ["Monitor Stand", "Keyboard", "Mouse Pad", "Cable Organizer"],
      carrier: "FedEx Ground",
    },
  },
  {
    barcode: "IZ6D5567123489021",
    packageId: "03-122-2366",
    vendor: "UPS",
    dataReceived: "2026-06-30 11:47",
    itemValues: "$54.20",
    weight: "0.6 kg",
    status: "Ready to Send",
    details: {
      recipient: "S. Chen",
      address: "3 Harbor View, Leeds",
      items: ["Phone Case"],
      carrier: "UPS Standard",
    },
  },
  {
    barcode: "IZ6D543564733489021",
    packageId: "03-134-7453",
    vendor: "FedEx",
    dataReceived: "2026-06-30 11:47",
    itemValues: "$234.20",
    weight: "0.8 kg",
    status: "Ready to Send",
    details: {
      recipient: "S. Chen",
      address: "3 Harbor View, Leeds",
      items: ["Phone Case"],
      carrier: "UPS Standard",
    },
  },
];
export const COLUMNS = [
  {
    key: "vendor",
    label: "PackageId",
    sortable: true,
    width: "minmax(180px, 1.4fr)",
  },
  {
    key: "dataReceived",
    label: "Data Received",
    sortable: true,
    width: "minmax(160px, 1fr)",
  },
  {
    key: "itemValues",
    label: "Item Values",
    sortable: true,
    width: "minmax(120px, 0.8fr)",
  },
  {
    key: "weight",
    label: "Weight",
    sortable: true,
    width: "minmax(100px, 0.7fr)",
  },
  {
    key: "status",
    label: "Status",
    sortable: true,
    width: "minmax(120px, 0.8fr)",
  },
  {
    key: "action",
    label: "Action",
    sortable: false,
    width: "minmax(90px, 0.6fr)",
  },
];
export const styles = [
  "min-w-30 flex-2 shrink-0 py-4",
  "min-w-30 flex-2 shrink-0 py-4",
  "min-w-30 flex-2 shrink-0 py-4",
  "min-w-20 flex-1 shrink-0 py-4",
  "min-w-20 flex-1 shrink-0 py-4 justify-center",
  "min-w-35 flex-1 shrink-0 py-4 justify-center",
  "min-w-20 flex-1 shrink-0 py-4 justify-center",
];
export const header = [
  { name: "Form", key: "vendor", sortable: true },
  { name: "PackageId", key: "packageId", sortable: true },
  { name: "Data Received", key: "dataReceived", sortable: true },
  { name: "Item Values", key: "itemValues", sortable: true },
  { name: "Weight", key: "weight", sortable: true },
  { name: "Status", key: "status", sortable: false },
  { name: "Action", key: "action", sortable: false },
];
