export const RAW_DATA = [
  {
    barcode: "IZ6A9426897731887",
    packageId: "03-218-9705",
    vendor: "Amazon",
    dataReceived: "2026-06-28 14:32",
    itemValues: "$99.00",
    totalValues: "$112.50",
    weight: "2.4 kg",
    status: {
      label: "In Review",
      details: "",
    },
    details: {
      recipient: "J. Whitfield",
      address: "14 Cross St, London",
      items: ["USB-C Cable", "Desk Lamp", "Notebook Set"],
      carrier: "Amazon Logistics",
    },
  },
  {
    barcode: "IZ6A9423125556541887",
    packageId: "03-854-9235",
    vendor: "Amazon",
    dataReceived: "2026-06-28 17:46",
    itemValues: "$19.00",
    totalValues: "$32.20",
    weight: "1.1 kg",
    status: {
      label: "In Review",
      details: "",
    },
    details: {
      recipient: "J. Whitfield",
      address: "14 Cross St, London",
      items: ["USB-C Cable", "Desk Lamp", "Notebook Set"],
      carrier: "Amazon Logistics",
    },
  },
  {
    barcode: "IZ6B1183420019234",
    packageId: "03-156-1255",
    vendor: "DHL",
    dataReceived: "2026-06-29 09:12",
    itemValues: "$89.00",
    totalValues: "$102.00",
    weight: "1.1 kg",
    status: {
      label: "Ready to Send",
      details: "",
    },
    details: {
      recipient: "M. Osei",
      address: "22 Baker Rd, Manchester",
      items: ["Running Shoes"],
      carrier: "DHL Express",
    },
  },
  {
    barcode: "IZ6C7729384610552",
    packageId: "03-345-1643",
    vendor: "FedEx",
    dataReceived: "2026-06-30 18:05",
    itemValues: "$310.75",
    totalValues: "$450.15",
    weight: "5.8 kg",
    status: {
      label: "Action Required",
      details: "Upload Merchant Invoice",
    },
    details: {
      recipient: "R. Patel",
      address: "9 Elm Court, Bristol",
      items: ["Monitor Stand", "Keyboard", "Mouse Pad", "Cable Organizer"],
      carrier: "FedEx Ground",
    },
  },
  {
    barcode: "IZ6D5567123489021",
    packageId: "03-122-2366",
    vendor: "UPS",
    dataReceived: "2026-06-30 11:47",
    itemValues: "$54.20",
    totalValues: "$79.00",
    weight: "0.6 kg",
    status: {
      label: "Ready to Send",
      details: "",
    },
    details: {
      recipient: "S. Chen",
      address: "3 Harbor View, Leeds",
      items: ["Phone Case"],
      carrier: "UPS Standard",
    },
  },
  {
    barcode: "IZ6D543564733489021",
    packageId: "03-134-7453",
    vendor: "FedEx",
    dataReceived: "2026-06-30 11:47",
    itemValues: "$234.20",
    totalValues: "$314.20",
    weight: "0.8 kg",
    status: {
      label: "Ready to Send",
      details: "",
    },
    details: {
      recipient: "S. Chen",
      address: "3 Harbor View, Leeds",
      items: ["Phone Case"],
      carrier: "UPS Standard",
    },
  },
];
export const COLUMNS = [
  {
    name: "Form",
    key: "vendor",
    sortable: true,
    tabs: ["View All", "Action Required", "In Review", "Ready to Send"],
    className: "min-w-30 flex-2 shrink-0 py-4",
  },
  {
    name: "PackageId",
    key: "packageId",
    sortable: true,
    tabs: ["View All", "Action Required", "In Review", "Ready to Send"],
    className: "min-w-25 flex-2 shrink-0 py-4",
  },
  {
    name: "Data Received",
    key: "dataReceived",
    sortable: true,
    tabs: ["View All", "Action Required", "In Review", "Ready to Send"],
    className: "min-w-20 flex-2 shrink-0 py-4",
  },
  {
    name: "Item Values",
    key: "itemValues",
    sortable: true,
    tabs: ["View All", "Ready to Send"],
    className: "min-w-20 flex-1 shrink-0 py-4",
  },
  {
    name: "Total Values",
    key: "totalValues",
    sortable: true,
    tabs: ["In Review"],
    className: "min-w-20 flex-1 shrink-0 py-4",
  },
  {
    name: "Weight",
    key: "weight",
    sortable: true,
    tabs: ["View All", "In Review", "Ready to Send"],
    className: "min-w-20 flex-1 shrink-0 py-4 justify-center",
  },
  {
    name: "Status",
    key: "status",
    sortable: false,
    tabs: ["View All", "Action Required"],
    className: "min-w-30 flex-2 shrink-0 py-4 justify-center",
  },
  {
    name: "Action",
    key: "action",
    sortable: false,
    tabs: ["View All", "Action Required", "In Review", "Ready to Send"],
    className: "min-w-25 flex-1 shrink-0 py-4 justify-center",
  },
];
